// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: campaign_service.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateCampaignRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Subject       string                 `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	FromName      string                 `protobuf:"bytes,3,opt,name=from_name,json=fromName,proto3" json:"from_name,omitempty"`
	FromEmail     string                 `protobuf:"bytes,4,opt,name=from_email,json=fromEmail,proto3" json:"from_email,omitempty"`
	TemplateId    string                 `protobuf:"bytes,5,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	ContactListId string                 `protobuf:"bytes,6,opt,name=contact_list_id,json=contactListId,proto3" json:"contact_list_id,omitempty"`
	Type          string                 `protobuf:"bytes,7,opt,name=type,proto3" json:"type,omitempty"`
	ScheduledAt   string                 `protobuf:"bytes,8,opt,name=scheduled_at,json=scheduledAt,proto3" json:"scheduled_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCampaignRequest) Reset() {
	*x = CreateCampaignRequest{}
	mi := &file_campaign_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCampaignRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCampaignRequest) ProtoMessage() {}

func (x *CreateCampaignRequest) ProtoReflect() protoreflect.Message {
	mi := &file_campaign_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCampaignRequest.ProtoReflect.Descriptor instead.
func (*CreateCampaignRequest) Descriptor() ([]byte, []int) {
	return file_campaign_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreateCampaignRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateCampaignRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *CreateCampaignRequest) GetFromName() string {
	if x != nil {
		return x.FromName
	}
	return ""
}

func (x *CreateCampaignRequest) GetFromEmail() string {
	if x != nil {
		return x.FromEmail
	}
	return ""
}

func (x *CreateCampaignRequest) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

func (x *CreateCampaignRequest) GetContactListId() string {
	if x != nil {
		return x.ContactListId
	}
	return ""
}

func (x *CreateCampaignRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreateCampaignRequest) GetScheduledAt() string {
	if x != nil {
		return x.ScheduledAt
	}
	return ""
}

type GetCampaignRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCampaignRequest) Reset() {
	*x = GetCampaignRequest{}
	mi := &file_campaign_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCampaignRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCampaignRequest) ProtoMessage() {}

func (x *GetCampaignRequest) ProtoReflect() protoreflect.Message {
	mi := &file_campaign_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCampaignRequest.ProtoReflect.Descriptor instead.
func (*GetCampaignRequest) Descriptor() ([]byte, []int) {
	return file_campaign_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetCampaignRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UpdateCampaignRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Subject       string                 `protobuf:"bytes,3,opt,name=subject,proto3" json:"subject,omitempty"`
	FromName      string                 `protobuf:"bytes,4,opt,name=from_name,json=fromName,proto3" json:"from_name,omitempty"`
	FromEmail     string                 `protobuf:"bytes,5,opt,name=from_email,json=fromEmail,proto3" json:"from_email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCampaignRequest) Reset() {
	*x = UpdateCampaignRequest{}
	mi := &file_campaign_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCampaignRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCampaignRequest) ProtoMessage() {}

func (x *UpdateCampaignRequest) ProtoReflect() protoreflect.Message {
	mi := &file_campaign_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCampaignRequest.ProtoReflect.Descriptor instead.
func (*UpdateCampaignRequest) Descriptor() ([]byte, []int) {
	return file_campaign_service_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateCampaignRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateCampaignRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateCampaignRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *UpdateCampaignRequest) GetFromName() string {
	if x != nil {
		return x.FromName
	}
	return ""
}

func (x *UpdateCampaignRequest) GetFromEmail() string {
	if x != nil {
		return x.FromEmail
	}
	return ""
}

type DeleteCampaignRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCampaignRequest) Reset() {
	*x = DeleteCampaignRequest{}
	mi := &file_campaign_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCampaignRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCampaignRequest) ProtoMessage() {}

func (x *DeleteCampaignRequest) ProtoReflect() protoreflect.Message {
	mi := &file_campaign_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCampaignRequest.ProtoReflect.Descriptor instead.
func (*DeleteCampaignRequest) Descriptor() ([]byte, []int) {
	return file_campaign_service_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteCampaignRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteCampaignResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCampaignResponse) Reset() {
	*x = DeleteCampaignResponse{}
	mi := &file_campaign_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCampaignResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCampaignResponse) ProtoMessage() {}

func (x *DeleteCampaignResponse) ProtoReflect() protoreflect.Message {
	mi := &file_campaign_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCampaignResponse.ProtoReflect.Descriptor instead.
func (*DeleteCampaignResponse) Descriptor() ([]byte, []int) {
	return file_campaign_service_proto_rawDescGZIP(), []int{4}
}

type ListCampaignsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Pagination    *Pagination            `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCampaignsRequest) Reset() {
	*x = ListCampaignsRequest{}
	mi := &file_campaign_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCampaignsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCampaignsRequest) ProtoMessage() {}

func (x *ListCampaignsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_campaign_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCampaignsRequest.ProtoReflect.Descriptor instead.
func (*ListCampaignsRequest) Descriptor() ([]byte, []int) {
	return file_campaign_service_proto_rawDescGZIP(), []int{5}
}

func (x *ListCampaignsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListCampaignsRequest) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ListCampaignsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Campaigns     []*Campaign            `protobuf:"bytes,1,rep,name=campaigns,proto3" json:"campaigns,omitempty"`
	Meta          *PaginationMeta        `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCampaignsResponse) Reset() {
	*x = ListCampaignsResponse{}
	mi := &file_campaign_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCampaignsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCampaignsResponse) ProtoMessage() {}

func (x *ListCampaignsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_campaign_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCampaignsResponse.ProtoReflect.Descriptor instead.
func (*ListCampaignsResponse) Descriptor() ([]byte, []int) {
	return file_campaign_service_proto_rawDescGZIP(), []int{6}
}

func (x *ListCampaignsResponse) GetCampaigns() []*Campaign {
	if x != nil {
		return x.Campaigns
	}
	return nil
}

func (x *ListCampaignsResponse) GetMeta() *PaginationMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

type LaunchCampaignRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LaunchCampaignRequest) Reset() {
	*x = LaunchCampaignRequest{}
	mi := &file_campaign_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LaunchCampaignRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LaunchCampaignRequest) ProtoMessage() {}

func (x *LaunchCampaignRequest) ProtoReflect() protoreflect.Message {
	mi := &file_campaign_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LaunchCampaignRequest.ProtoReflect.Descriptor instead.
func (*LaunchCampaignRequest) Descriptor() ([]byte, []int) {
	return file_campaign_service_proto_rawDescGZIP(), []int{7}
}

func (x *LaunchCampaignRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type PauseCampaignRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PauseCampaignRequest) Reset() {
	*x = PauseCampaignRequest{}
	mi := &file_campaign_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PauseCampaignRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PauseCampaignRequest) ProtoMessage() {}

func (x *PauseCampaignRequest) ProtoReflect() protoreflect.Message {
	mi := &file_campaign_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PauseCampaignRequest.ProtoReflect.Descriptor instead.
func (*PauseCampaignRequest) Descriptor() ([]byte, []int) {
	return file_campaign_service_proto_rawDescGZIP(), []int{8}
}

func (x *PauseCampaignRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ResumeCampaignRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeCampaignRequest) Reset() {
	*x = ResumeCampaignRequest{}
	mi := &file_campaign_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeCampaignRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeCampaignRequest) ProtoMessage() {}

func (x *ResumeCampaignRequest) ProtoReflect() protoreflect.Message {
	mi := &file_campaign_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeCampaignRequest.ProtoReflect.Descriptor instead.
func (*ResumeCampaignRequest) Descriptor() ([]byte, []int) {
	return file_campaign_service_proto_rawDescGZIP(), []int{9}
}

func (x *ResumeCampaignRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CancelCampaignRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelCampaignRequest) Reset() {
	*x = CancelCampaignRequest{}
	mi := &file_campaign_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelCampaignRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelCampaignRequest) ProtoMessage() {}

func (x *CancelCampaignRequest) ProtoReflect() protoreflect.Message {
	mi := &file_campaign_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelCampaignRequest.ProtoReflect.Descriptor instead.
func (*CancelCampaignRequest) Descriptor() ([]byte, []int) {
	return file_campaign_service_proto_rawDescGZIP(), []int{10}
}

func (x *CancelCampaignRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type Campaign struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OrgId           string                 `protobuf:"bytes,2,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	Name            string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Subject         string                 `protobuf:"bytes,4,opt,name=subject,proto3" json:"subject,omitempty"`
	FromName        string                 `protobuf:"bytes,5,opt,name=from_name,json=fromName,proto3" json:"from_name,omitempty"`
	FromEmail       string                 `protobuf:"bytes,6,opt,name=from_email,json=fromEmail,proto3" json:"from_email,omitempty"`
	Type            string                 `protobuf:"bytes,7,opt,name=type,proto3" json:"type,omitempty"`
	Status          string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	TotalRecipients int32                  `protobuf:"varint,9,opt,name=total_recipients,json=totalRecipients,proto3" json:"total_recipients,omitempty"`
	SentCount       int32                  `protobuf:"varint,10,opt,name=sent_count,json=sentCount,proto3" json:"sent_count,omitempty"`
	FailedCount     int32                  `protobuf:"varint,11,opt,name=failed_count,json=failedCount,proto3" json:"failed_count,omitempty"`
	CreatedAt       string                 `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       string                 `protobuf:"bytes,13,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Campaign) Reset() {
	*x = Campaign{}
	mi := &file_campaign_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Campaign) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Campaign) ProtoMessage() {}

func (x *Campaign) ProtoReflect() protoreflect.Message {
	mi := &file_campaign_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Campaign.ProtoReflect.Descriptor instead.
func (*Campaign) Descriptor() ([]byte, []int) {
	return file_campaign_service_proto_rawDescGZIP(), []int{11}
}

func (x *Campaign) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Campaign) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *Campaign) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Campaign) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *Campaign) GetFromName() string {
	if x != nil {
		return x.FromName
	}
	return ""
}

func (x *Campaign) GetFromEmail() string {
	if x != nil {
		return x.FromEmail
	}
	return ""
}

func (x *Campaign) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Campaign) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Campaign) GetTotalRecipients() int32 {
	if x != nil {
		return x.TotalRecipients
	}
	return 0
}

func (x *Campaign) GetSentCount() int32 {
	if x != nil {
		return x.SentCount
	}
	return 0
}

func (x *Campaign) GetFailedCount() int32 {
	if x != nil {
		return x.FailedCount
	}
	return 0
}

func (x *Campaign) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Campaign) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

var File_campaign_service_proto protoreflect.FileDescriptor

const file_campaign_service_proto_rawDesc = "" +
	"\n" +
	"\x16campaign_service.proto\x12\tmailos.v1\x1a\fcommon.proto\"\x81\x02\n" +
	"\x15CreateCampaignRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\asubject\x18\x02 \x01(\tR\asubject\x12\x1b\n" +
	"\tfrom_name\x18\x03 \x01(\tR\bfromName\x12\x1d\n" +
	"\n" +
	"from_email\x18\x04 \x01(\tR\tfromEmail\x12\x1f\n" +
	"\vtemplate_id\x18\x05 \x01(\tR\n" +
	"templateId\x12&\n" +
	"\x0fcontact_list_id\x18\x06 \x01(\tR\rcontactListId\x12\x12\n" +
	"\x04type\x18\a \x01(\tR\x04type\x12!\n" +
	"\fscheduled_at\x18\b \x01(\tR\vscheduledAt\"$\n" +
	"\x12GetCampaignRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x91\x01\n" +
	"\x15UpdateCampaignRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\asubject\x18\x03 \x01(\tR\asubject\x12\x1b\n" +
	"\tfrom_name\x18\x04 \x01(\tR\bfromName\x12\x1d\n" +
	"\n" +
	"from_email\x18\x05 \x01(\tR\tfromEmail\"'\n" +
	"\x15DeleteCampaignRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x18\n" +
	"\x16DeleteCampaignResponse\"e\n" +
	"\x14ListCampaignsRequest\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x125\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x15.mailos.v1.PaginationR\n" +
	"pagination\"y\n" +
	"\x15ListCampaignsResponse\x121\n" +
	"\tcampaigns\x18\x01 \x03(\v2\x13.mailos.v1.CampaignR\tcampaigns\x12-\n" +
	"\x04meta\x18\x02 \x01(\v2\x19.mailos.v1.PaginationMetaR\x04meta\"'\n" +
	"\x15LaunchCampaignRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"&\n" +
	"\x14PauseCampaignRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"'\n" +
	"\x15ResumeCampaignRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"'\n" +
	"\x15CancelCampaignRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xf2\x02\n" +
	"\bCampaign\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x15\n" +
	"\x06org_id\x18\x02 \x01(\tR\x05orgId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x18\n" +
	"\asubject\x18\x04 \x01(\tR\asubject\x12\x1b\n" +
	"\tfrom_name\x18\x05 \x01(\tR\bfromName\x12\x1d\n" +
	"\n" +
	"from_email\x18\x06 \x01(\tR\tfromEmail\x12\x12\n" +
	"\x04type\x18\a \x01(\tR\x04type\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\x12)\n" +
	"\x10total_recipients\x18\t \x01(\x05R\x0ftotalRecipients\x12\x1d\n" +
	"\n" +
	"sent_count\x18\n" +
	" \x01(\x05R\tsentCount\x12!\n" +
	"\ffailed_count\x18\v \x01(\x05R\vfailedCount\x12\x1d\n" +
	"\n" +
	"created_at\x18\f \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\r \x01(\tR\tupdatedAt2\xb3\x05\n" +
	"\x0fCampaignService\x12G\n" +
	"\x0eCreateCampaign\x12 .mailos.v1.CreateCampaignRequest\x1a\x13.mailos.v1.Campaign\x12A\n" +
	"\vGetCampaign\x12\x1d.mailos.v1.GetCampaignRequest\x1a\x13.mailos.v1.Campaign\x12G\n" +
	"\x0eUpdateCampaign\x12 .mailos.v1.UpdateCampaignRequest\x1a\x13.mailos.v1.Campaign\x12U\n" +
	"\x0eDeleteCampaign\x12 .mailos.v1.DeleteCampaignRequest\x1a!.mailos.v1.DeleteCampaignResponse\x12R\n" +
	"\rListCampaigns\x12\x1f.mailos.v1.ListCampaignsRequest\x1a .mailos.v1.ListCampaignsResponse\x12G\n" +
	"\x0eLaunchCampaign\x12 .mailos.v1.LaunchCampaignRequest\x1a\x13.mailos.v1.Campaign\x12E\n" +
	"\rPauseCampaign\x12\x1f.mailos.v1.PauseCampaignRequest\x1a\x13.mailos.v1.Campaign\x12G\n" +
	"\x0eResumeCampaign\x12 .mailos.v1.ResumeCampaignRequest\x1a\x13.mailos.v1.Campaign\x12G\n" +
	"\x0eCancelCampaign\x12 .mailos.v1.CancelCampaignRequest\x1a\x13.mailos.v1.CampaignB5Z3github.com/razatechofficial/mail-os/api/proto/v1;v1b\x06proto3"

var (
	file_campaign_service_proto_rawDescOnce sync.Once
	file_campaign_service_proto_rawDescData []byte
)

func file_campaign_service_proto_rawDescGZIP() []byte {
	file_campaign_service_proto_rawDescOnce.Do(func() {
		file_campaign_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_campaign_service_proto_rawDesc), len(file_campaign_service_proto_rawDesc)))
	})
	return file_campaign_service_proto_rawDescData
}

var file_campaign_service_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_campaign_service_proto_goTypes = []any{
	(*CreateCampaignRequest)(nil),  // 0: mailos.v1.CreateCampaignRequest
	(*GetCampaignRequest)(nil),     // 1: mailos.v1.GetCampaignRequest
	(*UpdateCampaignRequest)(nil),  // 2: mailos.v1.UpdateCampaignRequest
	(*DeleteCampaignRequest)(nil),  // 3: mailos.v1.DeleteCampaignRequest
	(*DeleteCampaignResponse)(nil), // 4: mailos.v1.DeleteCampaignResponse
	(*ListCampaignsRequest)(nil),   // 5: mailos.v1.ListCampaignsRequest
	(*ListCampaignsResponse)(nil),  // 6: mailos.v1.ListCampaignsResponse
	(*LaunchCampaignRequest)(nil),  // 7: mailos.v1.LaunchCampaignRequest
	(*PauseCampaignRequest)(nil),   // 8: mailos.v1.PauseCampaignRequest
	(*ResumeCampaignRequest)(nil),  // 9: mailos.v1.ResumeCampaignRequest
	(*CancelCampaignRequest)(nil),  // 10: mailos.v1.CancelCampaignRequest
	(*Campaign)(nil),               // 11: mailos.v1.Campaign
	(*Pagination)(nil),             // 12: mailos.v1.Pagination
	(*PaginationMeta)(nil),         // 13: mailos.v1.PaginationMeta
}
var file_campaign_service_proto_depIdxs = []int32{
	12, // 0: mailos.v1.ListCampaignsRequest.pagination:type_name -> mailos.v1.Pagination
	11, // 1: mailos.v1.ListCampaignsResponse.campaigns:type_name -> mailos.v1.Campaign
	13, // 2: mailos.v1.ListCampaignsResponse.meta:type_name -> mailos.v1.PaginationMeta
	0,  // 3: mailos.v1.CampaignService.CreateCampaign:input_type -> mailos.v1.CreateCampaignRequest
	1,  // 4: mailos.v1.CampaignService.GetCampaign:input_type -> mailos.v1.GetCampaignRequest
	2,  // 5: mailos.v1.CampaignService.UpdateCampaign:input_type -> mailos.v1.UpdateCampaignRequest
	3,  // 6: mailos.v1.CampaignService.DeleteCampaign:input_type -> mailos.v1.DeleteCampaignRequest
	5,  // 7: mailos.v1.CampaignService.ListCampaigns:input_type -> mailos.v1.ListCampaignsRequest
	7,  // 8: mailos.v1.CampaignService.LaunchCampaign:input_type -> mailos.v1.LaunchCampaignRequest
	8,  // 9: mailos.v1.CampaignService.PauseCampaign:input_type -> mailos.v1.PauseCampaignRequest
	9,  // 10: mailos.v1.CampaignService.ResumeCampaign:input_type -> mailos.v1.ResumeCampaignRequest
	10, // 11: mailos.v1.CampaignService.CancelCampaign:input_type -> mailos.v1.CancelCampaignRequest
	11, // 12: mailos.v1.CampaignService.CreateCampaign:output_type -> mailos.v1.Campaign
	11, // 13: mailos.v1.CampaignService.GetCampaign:output_type -> mailos.v1.Campaign
	11, // 14: mailos.v1.CampaignService.UpdateCampaign:output_type -> mailos.v1.Campaign
	4,  // 15: mailos.v1.CampaignService.DeleteCampaign:output_type -> mailos.v1.DeleteCampaignResponse
	6,  // 16: mailos.v1.CampaignService.ListCampaigns:output_type -> mailos.v1.ListCampaignsResponse
	11, // 17: mailos.v1.CampaignService.LaunchCampaign:output_type -> mailos.v1.Campaign
	11, // 18: mailos.v1.CampaignService.PauseCampaign:output_type -> mailos.v1.Campaign
	11, // 19: mailos.v1.CampaignService.ResumeCampaign:output_type -> mailos.v1.Campaign
	11, // 20: mailos.v1.CampaignService.CancelCampaign:output_type -> mailos.v1.Campaign
	12, // [12:21] is the sub-list for method output_type
	3,  // [3:12] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_campaign_service_proto_init() }
func file_campaign_service_proto_init() {
	if File_campaign_service_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_campaign_service_proto_rawDesc), len(file_campaign_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_campaign_service_proto_goTypes,
		DependencyIndexes: file_campaign_service_proto_depIdxs,
		MessageInfos:      file_campaign_service_proto_msgTypes,
	}.Build()
	File_campaign_service_proto = out.File
	file_campaign_service_proto_goTypes = nil
	file_campaign_service_proto_depIdxs = nil
}
