// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: mail_service.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendEmailRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	FromName       string                 `protobuf:"bytes,1,opt,name=from_name,json=fromName,proto3" json:"from_name,omitempty"`
	FromEmail      string                 `protobuf:"bytes,2,opt,name=from_email,json=fromEmail,proto3" json:"from_email,omitempty"`
	ToEmail        string                 `protobuf:"bytes,3,opt,name=to_email,json=toEmail,proto3" json:"to_email,omitempty"`
	ToName         string                 `protobuf:"bytes,4,opt,name=to_name,json=toName,proto3" json:"to_name,omitempty"`
	Subject        string                 `protobuf:"bytes,5,opt,name=subject,proto3" json:"subject,omitempty"`
	HtmlBody       string                 `protobuf:"bytes,6,opt,name=html_body,json=htmlBody,proto3" json:"html_body,omitempty"`
	TextBody       string                 `protobuf:"bytes,7,opt,name=text_body,json=textBody,proto3" json:"text_body,omitempty"`
	TemplateSlug   string                 `protobuf:"bytes,8,opt,name=template_slug,json=templateSlug,proto3" json:"template_slug,omitempty"`
	TemplateVars   map[string]string      `protobuf:"bytes,9,rep,name=template_vars,json=templateVars,proto3" json:"template_vars,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Tags           []string               `protobuf:"bytes,10,rep,name=tags,proto3" json:"tags,omitempty"`
	Priority       int32                  `protobuf:"varint,11,opt,name=priority,proto3" json:"priority,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,12,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SendEmailRequest) Reset() {
	*x = SendEmailRequest{}
	mi := &file_mail_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendEmailRequest) ProtoMessage() {}

func (x *SendEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mail_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendEmailRequest.ProtoReflect.Descriptor instead.
func (*SendEmailRequest) Descriptor() ([]byte, []int) {
	return file_mail_service_proto_rawDescGZIP(), []int{0}
}

func (x *SendEmailRequest) GetFromName() string {
	if x != nil {
		return x.FromName
	}
	return ""
}

func (x *SendEmailRequest) GetFromEmail() string {
	if x != nil {
		return x.FromEmail
	}
	return ""
}

func (x *SendEmailRequest) GetToEmail() string {
	if x != nil {
		return x.ToEmail
	}
	return ""
}

func (x *SendEmailRequest) GetToName() string {
	if x != nil {
		return x.ToName
	}
	return ""
}

func (x *SendEmailRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *SendEmailRequest) GetHtmlBody() string {
	if x != nil {
		return x.HtmlBody
	}
	return ""
}

func (x *SendEmailRequest) GetTextBody() string {
	if x != nil {
		return x.TextBody
	}
	return ""
}

func (x *SendEmailRequest) GetTemplateSlug() string {
	if x != nil {
		return x.TemplateSlug
	}
	return ""
}

func (x *SendEmailRequest) GetTemplateVars() map[string]string {
	if x != nil {
		return x.TemplateVars
	}
	return nil
}

func (x *SendEmailRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *SendEmailRequest) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *SendEmailRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type SendEmailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendEmailResponse) Reset() {
	*x = SendEmailResponse{}
	mi := &file_mail_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendEmailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendEmailResponse) ProtoMessage() {}

func (x *SendEmailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mail_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendEmailResponse.ProtoReflect.Descriptor instead.
func (*SendEmailResponse) Descriptor() ([]byte, []int) {
	return file_mail_service_proto_rawDescGZIP(), []int{1}
}

func (x *SendEmailResponse) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *SendEmailResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type BatchSendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*SendEmailRequest    `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchSendRequest) Reset() {
	*x = BatchSendRequest{}
	mi := &file_mail_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchSendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchSendRequest) ProtoMessage() {}

func (x *BatchSendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mail_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchSendRequest.ProtoReflect.Descriptor instead.
func (*BatchSendRequest) Descriptor() ([]byte, []int) {
	return file_mail_service_proto_rawDescGZIP(), []int{2}
}

func (x *BatchSendRequest) GetMessages() []*SendEmailRequest {
	if x != nil {
		return x.Messages
	}
	return nil
}

type BatchSendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*SendEmailResponse   `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	SuccessCount  int32                  `protobuf:"varint,2,opt,name=success_count,json=successCount,proto3" json:"success_count,omitempty"`
	FailCount     int32                  `protobuf:"varint,3,opt,name=fail_count,json=failCount,proto3" json:"fail_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchSendResponse) Reset() {
	*x = BatchSendResponse{}
	mi := &file_mail_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchSendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchSendResponse) ProtoMessage() {}

func (x *BatchSendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mail_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchSendResponse.ProtoReflect.Descriptor instead.
func (*BatchSendResponse) Descriptor() ([]byte, []int) {
	return file_mail_service_proto_rawDescGZIP(), []int{3}
}

func (x *BatchSendResponse) GetResults() []*SendEmailResponse {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *BatchSendResponse) GetSuccessCount() int32 {
	if x != nil {
		return x.SuccessCount
	}
	return 0
}

func (x *BatchSendResponse) GetFailCount() int32 {
	if x != nil {
		return x.FailCount
	}
	return 0
}

type GetMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessageRequest) Reset() {
	*x = GetMessageRequest{}
	mi := &file_mail_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessageRequest) ProtoMessage() {}

func (x *GetMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mail_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessageRequest.ProtoReflect.Descriptor instead.
func (*GetMessageRequest) Descriptor() ([]byte, []int) {
	return file_mail_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetMessageRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListMessagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Pagination    *Pagination            `protobuf:"bytes,3,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMessagesRequest) Reset() {
	*x = ListMessagesRequest{}
	mi := &file_mail_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMessagesRequest) ProtoMessage() {}

func (x *ListMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mail_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMessagesRequest.ProtoReflect.Descriptor instead.
func (*ListMessagesRequest) Descriptor() ([]byte, []int) {
	return file_mail_service_proto_rawDescGZIP(), []int{5}
}

func (x *ListMessagesRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListMessagesRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ListMessagesRequest) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ListMessagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*Message             `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	Meta          *PaginationMeta        `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMessagesResponse) Reset() {
	*x = ListMessagesResponse{}
	mi := &file_mail_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMessagesResponse) ProtoMessage() {}

func (x *ListMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mail_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMessagesResponse.ProtoReflect.Descriptor instead.
func (*ListMessagesResponse) Descriptor() ([]byte, []int) {
	return file_mail_service_proto_rawDescGZIP(), []int{6}
}

func (x *ListMessagesResponse) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *ListMessagesResponse) GetMeta() *PaginationMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OrgId         string                 `protobuf:"bytes,2,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	FromName      string                 `protobuf:"bytes,3,opt,name=from_name,json=fromName,proto3" json:"from_name,omitempty"`
	FromEmail     string                 `protobuf:"bytes,4,opt,name=from_email,json=fromEmail,proto3" json:"from_email,omitempty"`
	ToEmail       string                 `protobuf:"bytes,5,opt,name=to_email,json=toEmail,proto3" json:"to_email,omitempty"`
	ToName        string                 `protobuf:"bytes,6,opt,name=to_name,json=toName,proto3" json:"to_name,omitempty"`
	Subject       string                 `protobuf:"bytes,7,opt,name=subject,proto3" json:"subject,omitempty"`
	Type          string                 `protobuf:"bytes,8,opt,name=type,proto3" json:"type,omitempty"`
	Status        string                 `protobuf:"bytes,9,opt,name=status,proto3" json:"status,omitempty"`
	Priority      int32                  `protobuf:"varint,10,opt,name=priority,proto3" json:"priority,omitempty"`
	Tags          []string               `protobuf:"bytes,11,rep,name=tags,proto3" json:"tags,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,13,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_mail_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_mail_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_mail_service_proto_rawDescGZIP(), []int{7}
}

func (x *Message) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Message) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *Message) GetFromName() string {
	if x != nil {
		return x.FromName
	}
	return ""
}

func (x *Message) GetFromEmail() string {
	if x != nil {
		return x.FromEmail
	}
	return ""
}

func (x *Message) GetToEmail() string {
	if x != nil {
		return x.ToEmail
	}
	return ""
}

func (x *Message) GetToName() string {
	if x != nil {
		return x.ToName
	}
	return ""
}

func (x *Message) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *Message) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Message) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Message) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *Message) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Message) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Message) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

var File_mail_service_proto protoreflect.FileDescriptor

const file_mail_service_proto_rawDesc = "" +
	"\n" +
	"\x12mail_service.proto\x12\tmailos.v1\x1a\fcommon.proto\"\xe9\x03\n" +
	"\x10SendEmailRequest\x12\x1b\n" +
	"\tfrom_name\x18\x01 \x01(\tR\bfromName\x12\x1d\n" +
	"\n" +
	"from_email\x18\x02 \x01(\tR\tfromEmail\x12\x19\n" +
	"\bto_email\x18\x03 \x01(\tR\atoEmail\x12\x17\n" +
	"\ato_name\x18\x04 \x01(\tR\x06toName\x12\x18\n" +
	"\asubject\x18\x05 \x01(\tR\asubject\x12\x1b\n" +
	"\thtml_body\x18\x06 \x01(\tR\bhtmlBody\x12\x1b\n" +
	"\ttext_body\x18\a \x01(\tR\btextBody\x12#\n" +
	"\rtemplate_slug\x18\b \x01(\tR\ftemplateSlug\x12R\n" +
	"\rtemplate_vars\x18\t \x03(\v2-.mailos.v1.SendEmailRequest.TemplateVarsEntryR\ftemplateVars\x12\x12\n" +
	"\x04tags\x18\n" +
	" \x03(\tR\x04tags\x12\x1a\n" +
	"\bpriority\x18\v \x01(\x05R\bpriority\x12'\n" +
	"\x0fidempotency_key\x18\f \x01(\tR\x0eidempotencyKey\x1a?\n" +
	"\x11TemplateVarsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"J\n" +
	"\x11SendEmailResponse\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"K\n" +
	"\x10BatchSendRequest\x127\n" +
	"\bmessages\x18\x01 \x03(\v2\x1b.mailos.v1.SendEmailRequestR\bmessages\"\x8f\x01\n" +
	"\x11BatchSendResponse\x126\n" +
	"\aresults\x18\x01 \x03(\v2\x1c.mailos.v1.SendEmailResponseR\aresults\x12#\n" +
	"\rsuccess_count\x18\x02 \x01(\x05R\fsuccessCount\x12\x1d\n" +
	"\n" +
	"fail_count\x18\x03 \x01(\x05R\tfailCount\"#\n" +
	"\x11GetMessageRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"x\n" +
	"\x13ListMessagesRequest\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x125\n" +
	"\n" +
	"pagination\x18\x03 \x01(\v2\x15.mailos.v1.PaginationR\n" +
	"pagination\"u\n" +
	"\x14ListMessagesResponse\x12.\n" +
	"\bmessages\x18\x01 \x03(\v2\x12.mailos.v1.MessageR\bmessages\x12-\n" +
	"\x04meta\x18\x02 \x01(\v2\x19.mailos.v1.PaginationMetaR\x04meta\"\xd4\x02\n" +
	"\aMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x15\n" +
	"\x06org_id\x18\x02 \x01(\tR\x05orgId\x12\x1b\n" +
	"\tfrom_name\x18\x03 \x01(\tR\bfromName\x12\x1d\n" +
	"\n" +
	"from_email\x18\x04 \x01(\tR\tfromEmail\x12\x19\n" +
	"\bto_email\x18\x05 \x01(\tR\atoEmail\x12\x17\n" +
	"\ato_name\x18\x06 \x01(\tR\x06toName\x12\x18\n" +
	"\asubject\x18\a \x01(\tR\asubject\x12\x12\n" +
	"\x04type\x18\b \x01(\tR\x04type\x12\x16\n" +
	"\x06status\x18\t \x01(\tR\x06status\x12\x1a\n" +
	"\bpriority\x18\n" +
	" \x01(\x05R\bpriority\x12\x12\n" +
	"\x04tags\x18\v \x03(\tR\x04tags\x12\x1d\n" +
	"\n" +
	"created_at\x18\f \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\r \x01(\tR\tupdatedAt2\xae\x02\n" +
	"\vMailService\x12F\n" +
	"\tSendEmail\x12\x1b.mailos.v1.SendEmailRequest\x1a\x1c.mailos.v1.SendEmailResponse\x12F\n" +
	"\tBatchSend\x12\x1b.mailos.v1.BatchSendRequest\x1a\x1c.mailos.v1.BatchSendResponse\x12>\n" +
	"\n" +
	"GetMessage\x12\x1c.mailos.v1.GetMessageRequest\x1a\x12.mailos.v1.Message\x12O\n" +
	"\fListMessages\x12\x1e.mailos.v1.ListMessagesRequest\x1a\x1f.mailos.v1.ListMessagesResponseB5Z3github.com/razatechofficial/mail-os/api/proto/v1;v1b\x06proto3"

var (
	file_mail_service_proto_rawDescOnce sync.Once
	file_mail_service_proto_rawDescData []byte
)

func file_mail_service_proto_rawDescGZIP() []byte {
	file_mail_service_proto_rawDescOnce.Do(func() {
		file_mail_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mail_service_proto_rawDesc), len(file_mail_service_proto_rawDesc)))
	})
	return file_mail_service_proto_rawDescData
}

var file_mail_service_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_mail_service_proto_goTypes = []any{
	(*SendEmailRequest)(nil),     // 0: mailos.v1.SendEmailRequest
	(*SendEmailResponse)(nil),    // 1: mailos.v1.SendEmailResponse
	(*BatchSendRequest)(nil),     // 2: mailos.v1.BatchSendRequest
	(*BatchSendResponse)(nil),    // 3: mailos.v1.BatchSendResponse
	(*GetMessageRequest)(nil),    // 4: mailos.v1.GetMessageRequest
	(*ListMessagesRequest)(nil),  // 5: mailos.v1.ListMessagesRequest
	(*ListMessagesResponse)(nil), // 6: mailos.v1.ListMessagesResponse
	(*Message)(nil),              // 7: mailos.v1.Message
	nil,                          // 8: mailos.v1.SendEmailRequest.TemplateVarsEntry
	(*Pagination)(nil),           // 9: mailos.v1.Pagination
	(*PaginationMeta)(nil),       // 10: mailos.v1.PaginationMeta
}
var file_mail_service_proto_depIdxs = []int32{
	8,  // 0: mailos.v1.SendEmailRequest.template_vars:type_name -> mailos.v1.SendEmailRequest.TemplateVarsEntry
	0,  // 1: mailos.v1.BatchSendRequest.messages:type_name -> mailos.v1.SendEmailRequest
	1,  // 2: mailos.v1.BatchSendResponse.results:type_name -> mailos.v1.SendEmailResponse
	9,  // 3: mailos.v1.ListMessagesRequest.pagination:type_name -> mailos.v1.Pagination
	7,  // 4: mailos.v1.ListMessagesResponse.messages:type_name -> mailos.v1.Message
	10, // 5: mailos.v1.ListMessagesResponse.meta:type_name -> mailos.v1.PaginationMeta
	0,  // 6: mailos.v1.MailService.SendEmail:input_type -> mailos.v1.SendEmailRequest
	2,  // 7: mailos.v1.MailService.BatchSend:input_type -> mailos.v1.BatchSendRequest
	4,  // 8: mailos.v1.MailService.GetMessage:input_type -> mailos.v1.GetMessageRequest
	5,  // 9: mailos.v1.MailService.ListMessages:input_type -> mailos.v1.ListMessagesRequest
	1,  // 10: mailos.v1.MailService.SendEmail:output_type -> mailos.v1.SendEmailResponse
	3,  // 11: mailos.v1.MailService.BatchSend:output_type -> mailos.v1.BatchSendResponse
	7,  // 12: mailos.v1.MailService.GetMessage:output_type -> mailos.v1.Message
	6,  // 13: mailos.v1.MailService.ListMessages:output_type -> mailos.v1.ListMessagesResponse
	10, // [10:14] is the sub-list for method output_type
	6,  // [6:10] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_mail_service_proto_init() }
func file_mail_service_proto_init() {
	if File_mail_service_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mail_service_proto_rawDesc), len(file_mail_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mail_service_proto_goTypes,
		DependencyIndexes: file_mail_service_proto_depIdxs,
		MessageInfos:      file_mail_service_proto_msgTypes,
	}.Build()
	File_mail_service_proto = out.File
	file_mail_service_proto_goTypes = nil
	file_mail_service_proto_depIdxs = nil
}
