// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: template_service.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateTemplateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Slug          string                 `protobuf:"bytes,2,opt,name=slug,proto3" json:"slug,omitempty"`
	Category      string                 `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTemplateRequest) Reset() {
	*x = CreateTemplateRequest{}
	mi := &file_template_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTemplateRequest) ProtoMessage() {}

func (x *CreateTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_template_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTemplateRequest.ProtoReflect.Descriptor instead.
func (*CreateTemplateRequest) Descriptor() ([]byte, []int) {
	return file_template_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreateTemplateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateTemplateRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *CreateTemplateRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *CreateTemplateRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type GetTemplateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTemplateRequest) Reset() {
	*x = GetTemplateRequest{}
	mi := &file_template_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTemplateRequest) ProtoMessage() {}

func (x *GetTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_template_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTemplateRequest.ProtoReflect.Descriptor instead.
func (*GetTemplateRequest) Descriptor() ([]byte, []int) {
	return file_template_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetTemplateRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UpdateTemplateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	IsActive      bool                   `protobuf:"varint,4,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTemplateRequest) Reset() {
	*x = UpdateTemplateRequest{}
	mi := &file_template_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTemplateRequest) ProtoMessage() {}

func (x *UpdateTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_template_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTemplateRequest.ProtoReflect.Descriptor instead.
func (*UpdateTemplateRequest) Descriptor() ([]byte, []int) {
	return file_template_service_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateTemplateRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateTemplateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateTemplateRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateTemplateRequest) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

type DeleteTemplateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTemplateRequest) Reset() {
	*x = DeleteTemplateRequest{}
	mi := &file_template_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTemplateRequest) ProtoMessage() {}

func (x *DeleteTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_template_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTemplateRequest.ProtoReflect.Descriptor instead.
func (*DeleteTemplateRequest) Descriptor() ([]byte, []int) {
	return file_template_service_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteTemplateRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteTemplateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTemplateResponse) Reset() {
	*x = DeleteTemplateResponse{}
	mi := &file_template_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTemplateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTemplateResponse) ProtoMessage() {}

func (x *DeleteTemplateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_template_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTemplateResponse.ProtoReflect.Descriptor instead.
func (*DeleteTemplateResponse) Descriptor() ([]byte, []int) {
	return file_template_service_proto_rawDescGZIP(), []int{4}
}

type ListTemplatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pagination    *Pagination            `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTemplatesRequest) Reset() {
	*x = ListTemplatesRequest{}
	mi := &file_template_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTemplatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTemplatesRequest) ProtoMessage() {}

func (x *ListTemplatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_template_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTemplatesRequest.ProtoReflect.Descriptor instead.
func (*ListTemplatesRequest) Descriptor() ([]byte, []int) {
	return file_template_service_proto_rawDescGZIP(), []int{5}
}

func (x *ListTemplatesRequest) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ListTemplatesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Templates     []*Template            `protobuf:"bytes,1,rep,name=templates,proto3" json:"templates,omitempty"`
	Meta          *PaginationMeta        `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTemplatesResponse) Reset() {
	*x = ListTemplatesResponse{}
	mi := &file_template_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTemplatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTemplatesResponse) ProtoMessage() {}

func (x *ListTemplatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_template_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTemplatesResponse.ProtoReflect.Descriptor instead.
func (*ListTemplatesResponse) Descriptor() ([]byte, []int) {
	return file_template_service_proto_rawDescGZIP(), []int{6}
}

func (x *ListTemplatesResponse) GetTemplates() []*Template {
	if x != nil {
		return x.Templates
	}
	return nil
}

func (x *ListTemplatesResponse) GetMeta() *PaginationMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

type CreateVersionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TemplateId    string                 `protobuf:"bytes,1,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	Subject       string                 `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	HtmlBody      string                 `protobuf:"bytes,3,opt,name=html_body,json=htmlBody,proto3" json:"html_body,omitempty"`
	TextBody      string                 `protobuf:"bytes,4,opt,name=text_body,json=textBody,proto3" json:"text_body,omitempty"`
	Variables     []string               `protobuf:"bytes,5,rep,name=variables,proto3" json:"variables,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVersionRequest) Reset() {
	*x = CreateVersionRequest{}
	mi := &file_template_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVersionRequest) ProtoMessage() {}

func (x *CreateVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_template_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVersionRequest.ProtoReflect.Descriptor instead.
func (*CreateVersionRequest) Descriptor() ([]byte, []int) {
	return file_template_service_proto_rawDescGZIP(), []int{7}
}

func (x *CreateVersionRequest) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

func (x *CreateVersionRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *CreateVersionRequest) GetHtmlBody() string {
	if x != nil {
		return x.HtmlBody
	}
	return ""
}

func (x *CreateVersionRequest) GetTextBody() string {
	if x != nil {
		return x.TextBody
	}
	return ""
}

func (x *CreateVersionRequest) GetVariables() []string {
	if x != nil {
		return x.Variables
	}
	return nil
}

type ListVersionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TemplateId    string                 `protobuf:"bytes,1,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVersionsRequest) Reset() {
	*x = ListVersionsRequest{}
	mi := &file_template_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVersionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVersionsRequest) ProtoMessage() {}

func (x *ListVersionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_template_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVersionsRequest.ProtoReflect.Descriptor instead.
func (*ListVersionsRequest) Descriptor() ([]byte, []int) {
	return file_template_service_proto_rawDescGZIP(), []int{8}
}

func (x *ListVersionsRequest) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

type ListVersionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Versions      []*TemplateVersion     `protobuf:"bytes,1,rep,name=versions,proto3" json:"versions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVersionsResponse) Reset() {
	*x = ListVersionsResponse{}
	mi := &file_template_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVersionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVersionsResponse) ProtoMessage() {}

func (x *ListVersionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_template_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVersionsResponse.ProtoReflect.Descriptor instead.
func (*ListVersionsResponse) Descriptor() ([]byte, []int) {
	return file_template_service_proto_rawDescGZIP(), []int{9}
}

func (x *ListVersionsResponse) GetVersions() []*TemplateVersion {
	if x != nil {
		return x.Versions
	}
	return nil
}

type Template struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OrgId         string                 `protobuf:"bytes,2,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Slug          string                 `protobuf:"bytes,4,opt,name=slug,proto3" json:"slug,omitempty"`
	Category      string                 `protobuf:"bytes,5,opt,name=category,proto3" json:"category,omitempty"`
	Description   string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	IsActive      bool                   `protobuf:"varint,7,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Template) Reset() {
	*x = Template{}
	mi := &file_template_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Template) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Template) ProtoMessage() {}

func (x *Template) ProtoReflect() protoreflect.Message {
	mi := &file_template_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Template.ProtoReflect.Descriptor instead.
func (*Template) Descriptor() ([]byte, []int) {
	return file_template_service_proto_rawDescGZIP(), []int{10}
}

func (x *Template) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Template) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *Template) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Template) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *Template) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Template) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Template) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *Template) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Template) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type TemplateVersion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TemplateId    string                 `protobuf:"bytes,2,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	Version       int32                  `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	Subject       string                 `protobuf:"bytes,4,opt,name=subject,proto3" json:"subject,omitempty"`
	HtmlBody      string                 `protobuf:"bytes,5,opt,name=html_body,json=htmlBody,proto3" json:"html_body,omitempty"`
	TextBody      string                 `protobuf:"bytes,6,opt,name=text_body,json=textBody,proto3" json:"text_body,omitempty"`
	Variables     []string               `protobuf:"bytes,7,rep,name=variables,proto3" json:"variables,omitempty"`
	IsActive      bool                   `protobuf:"varint,8,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TemplateVersion) Reset() {
	*x = TemplateVersion{}
	mi := &file_template_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TemplateVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemplateVersion) ProtoMessage() {}

func (x *TemplateVersion) ProtoReflect() protoreflect.Message {
	mi := &file_template_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemplateVersion.ProtoReflect.Descriptor instead.
func (*TemplateVersion) Descriptor() ([]byte, []int) {
	return file_template_service_proto_rawDescGZIP(), []int{11}
}

func (x *TemplateVersion) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TemplateVersion) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

func (x *TemplateVersion) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *TemplateVersion) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *TemplateVersion) GetHtmlBody() string {
	if x != nil {
		return x.HtmlBody
	}
	return ""
}

func (x *TemplateVersion) GetTextBody() string {
	if x != nil {
		return x.TextBody
	}
	return ""
}

func (x *TemplateVersion) GetVariables() []string {
	if x != nil {
		return x.Variables
	}
	return nil
}

func (x *TemplateVersion) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *TemplateVersion) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

var File_template_service_proto protoreflect.FileDescriptor

const file_template_service_proto_rawDesc = "" +
	"\n" +
	"\x16template_service.proto\x12\tmailos.v1\x1a\fcommon.proto\"}\n" +
	"\x15CreateTemplateRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04slug\x18\x02 \x01(\tR\x04slug\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\"$\n" +
	"\x12GetTemplateRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"z\n" +
	"\x15UpdateTemplateRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1b\n" +
	"\tis_active\x18\x04 \x01(\bR\bisActive\"'\n" +
	"\x15DeleteTemplateRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x18\n" +
	"\x16DeleteTemplateResponse\"M\n" +
	"\x14ListTemplatesRequest\x125\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2\x15.mailos.v1.PaginationR\n" +
	"pagination\"y\n" +
	"\x15ListTemplatesResponse\x121\n" +
	"\ttemplates\x18\x01 \x03(\v2\x13.mailos.v1.TemplateR\ttemplates\x12-\n" +
	"\x04meta\x18\x02 \x01(\v2\x19.mailos.v1.PaginationMetaR\x04meta\"\xa9\x01\n" +
	"\x14CreateVersionRequest\x12\x1f\n" +
	"\vtemplate_id\x18\x01 \x01(\tR\n" +
	"templateId\x12\x18\n" +
	"\asubject\x18\x02 \x01(\tR\asubject\x12\x1b\n" +
	"\thtml_body\x18\x03 \x01(\tR\bhtmlBody\x12\x1b\n" +
	"\ttext_body\x18\x04 \x01(\tR\btextBody\x12\x1c\n" +
	"\tvariables\x18\x05 \x03(\tR\tvariables\"6\n" +
	"\x13ListVersionsRequest\x12\x1f\n" +
	"\vtemplate_id\x18\x01 \x01(\tR\n" +
	"templateId\"N\n" +
	"\x14ListVersionsResponse\x126\n" +
	"\bversions\x18\x01 \x03(\v2\x1a.mailos.v1.TemplateVersionR\bversions\"\xf2\x01\n" +
	"\bTemplate\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x15\n" +
	"\x06org_id\x18\x02 \x01(\tR\x05orgId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04slug\x18\x04 \x01(\tR\x04slug\x12\x1a\n" +
	"\bcategory\x18\x05 \x01(\tR\bcategory\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x12\x1b\n" +
	"\tis_active\x18\a \x01(\bR\bisActive\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\t \x01(\tR\tupdatedAt\"\x8a\x02\n" +
	"\x0fTemplateVersion\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vtemplate_id\x18\x02 \x01(\tR\n" +
	"templateId\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x05R\aversion\x12\x18\n" +
	"\asubject\x18\x04 \x01(\tR\asubject\x12\x1b\n" +
	"\thtml_body\x18\x05 \x01(\tR\bhtmlBody\x12\x1b\n" +
	"\ttext_body\x18\x06 \x01(\tR\btextBody\x12\x1c\n" +
	"\tvariables\x18\a \x03(\tR\tvariables\x12\x1b\n" +
	"\tis_active\x18\b \x01(\bR\bisActive\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\tR\tcreatedAt2\xb0\x04\n" +
	"\x0fTemplateService\x12G\n" +
	"\x0eCreateTemplate\x12 .mailos.v1.CreateTemplateRequest\x1a\x13.mailos.v1.Template\x12A\n" +
	"\vGetTemplate\x12\x1d.mailos.v1.GetTemplateRequest\x1a\x13.mailos.v1.Template\x12G\n" +
	"\x0eUpdateTemplate\x12 .mailos.v1.UpdateTemplateRequest\x1a\x13.mailos.v1.Template\x12U\n" +
	"\x0eDeleteTemplate\x12 .mailos.v1.DeleteTemplateRequest\x1a!.mailos.v1.DeleteTemplateResponse\x12R\n" +
	"\rListTemplates\x12\x1f.mailos.v1.ListTemplatesRequest\x1a .mailos.v1.ListTemplatesResponse\x12L\n" +
	"\rCreateVersion\x12\x1f.mailos.v1.CreateVersionRequest\x1a\x1a.mailos.v1.TemplateVersion\x12O\n" +
	"\fListVersions\x12\x1e.mailos.v1.ListVersionsRequest\x1a\x1f.mailos.v1.ListVersionsResponseB5Z3github.com/razatechofficial/mail-os/api/proto/v1;v1b\x06proto3"

var (
	file_template_service_proto_rawDescOnce sync.Once
	file_template_service_proto_rawDescData []byte
)

func file_template_service_proto_rawDescGZIP() []byte {
	file_template_service_proto_rawDescOnce.Do(func() {
		file_template_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_template_service_proto_rawDesc), len(file_template_service_proto_rawDesc)))
	})
	return file_template_service_proto_rawDescData
}

var file_template_service_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_template_service_proto_goTypes = []any{
	(*CreateTemplateRequest)(nil),  // 0: mailos.v1.CreateTemplateRequest
	(*GetTemplateRequest)(nil),     // 1: mailos.v1.GetTemplateRequest
	(*UpdateTemplateRequest)(nil),  // 2: mailos.v1.UpdateTemplateRequest
	(*DeleteTemplateRequest)(nil),  // 3: mailos.v1.DeleteTemplateRequest
	(*DeleteTemplateResponse)(nil), // 4: mailos.v1.DeleteTemplateResponse
	(*ListTemplatesRequest)(nil),   // 5: mailos.v1.ListTemplatesRequest
	(*ListTemplatesResponse)(nil),  // 6: mailos.v1.ListTemplatesResponse
	(*CreateVersionRequest)(nil),   // 7: mailos.v1.CreateVersionRequest
	(*ListVersionsRequest)(nil),    // 8: mailos.v1.ListVersionsRequest
	(*ListVersionsResponse)(nil),   // 9: mailos.v1.ListVersionsResponse
	(*Template)(nil),               // 10: mailos.v1.Template
	(*TemplateVersion)(nil),        // 11: mailos.v1.TemplateVersion
	(*Pagination)(nil),             // 12: mailos.v1.Pagination
	(*PaginationMeta)(nil),         // 13: mailos.v1.PaginationMeta
}
var file_template_service_proto_depIdxs = []int32{
	12, // 0: mailos.v1.ListTemplatesRequest.pagination:type_name -> mailos.v1.Pagination
	10, // 1: mailos.v1.ListTemplatesResponse.templates:type_name -> mailos.v1.Template
	13, // 2: mailos.v1.ListTemplatesResponse.meta:type_name -> mailos.v1.PaginationMeta
	11, // 3: mailos.v1.ListVersionsResponse.versions:type_name -> mailos.v1.TemplateVersion
	0,  // 4: mailos.v1.TemplateService.CreateTemplate:input_type -> mailos.v1.CreateTemplateRequest
	1,  // 5: mailos.v1.TemplateService.GetTemplate:input_type -> mailos.v1.GetTemplateRequest
	2,  // 6: mailos.v1.TemplateService.UpdateTemplate:input_type -> mailos.v1.UpdateTemplateRequest
	3,  // 7: mailos.v1.TemplateService.DeleteTemplate:input_type -> mailos.v1.DeleteTemplateRequest
	5,  // 8: mailos.v1.TemplateService.ListTemplates:input_type -> mailos.v1.ListTemplatesRequest
	7,  // 9: mailos.v1.TemplateService.CreateVersion:input_type -> mailos.v1.CreateVersionRequest
	8,  // 10: mailos.v1.TemplateService.ListVersions:input_type -> mailos.v1.ListVersionsRequest
	10, // 11: mailos.v1.TemplateService.CreateTemplate:output_type -> mailos.v1.Template
	10, // 12: mailos.v1.TemplateService.GetTemplate:output_type -> mailos.v1.Template
	10, // 13: mailos.v1.TemplateService.UpdateTemplate:output_type -> mailos.v1.Template
	4,  // 14: mailos.v1.TemplateService.DeleteTemplate:output_type -> mailos.v1.DeleteTemplateResponse
	6,  // 15: mailos.v1.TemplateService.ListTemplates:output_type -> mailos.v1.ListTemplatesResponse
	11, // 16: mailos.v1.TemplateService.CreateVersion:output_type -> mailos.v1.TemplateVersion
	9,  // 17: mailos.v1.TemplateService.ListVersions:output_type -> mailos.v1.ListVersionsResponse
	11, // [11:18] is the sub-list for method output_type
	4,  // [4:11] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_template_service_proto_init() }
func file_template_service_proto_init() {
	if File_template_service_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_template_service_proto_rawDesc), len(file_template_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_template_service_proto_goTypes,
		DependencyIndexes: file_template_service_proto_depIdxs,
		MessageInfos:      file_template_service_proto_msgTypes,
	}.Build()
	File_template_service_proto = out.File
	file_template_service_proto_goTypes = nil
	file_template_service_proto_depIdxs = nil
}
